# Generated by Django 2.2.14 on 2020-07-29 16:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('confidentiality_label', models.IntegerField(choices=[(1, 'TopSecret'), (2, 'Secret'), (3, 'Confidential'), (4, 'Unclassified')])),
                ('integrity_label', models.IntegerField(choices=[(1, 'VeryTrusted'), (2, 'Trusted'), (3, 'SlightlyTrusted'), (4, 'Untrusted')])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
