# Generated by Django 2.2.14 on 2020-08-01 02:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('confidentiality_label', models.IntegerField(choices=[(1, 'TopSecret'), (2, 'Secret'), (3, 'Confidential'), (4, 'Unclassified')])),
                ('integrity_label', models.IntegerField(choices=[(1, 'VeryTrusted'), (2, 'Trusted'), (3, 'SlightlyTrusted'), (4, 'Untrusted')])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TokenAuth',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.Token')),
                ('last_use', models.DateTimeField(auto_now=True)),
            ],
            bases=('authtoken.token',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=32)),
                ('data_file', models.FileField(upload_to='')),
                ('confidentiality_label', models.IntegerField(choices=[(1, 'TopSecret'), (2, 'Secret'), (3, 'Confidential'), (4, 'Unclassified')])),
                ('integrity_label', models.IntegerField(choices=[(1, 'VeryTrusted'), (2, 'Trusted'), (3, 'SlightlyTrusted'), (4, 'Untrusted')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
    ]
