# Generated by Django 2.2.14 on 2020-08-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='data_file',
        ),
    ]
