# Generated by Django 2.2.14 on 2020-07-31 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tokenauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=32)),
                ('confidentiality_label', models.IntegerField(choices=[(1, 'TopSecret'), (2, 'Secret'), (3, 'Confidential'), (4, 'Unclassified')])),
                ('integrity_label', models.IntegerField(choices=[(1, 'VeryTrusted'), (2, 'Trusted'), (3, 'SlightlyTrusted'), (4, 'Untrusted')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
    ]
