"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f!c+s-6t&^wa#-48ayx#yfd8g2aq2u4+3w=%3n6wfv#0+%f9q5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


P = ("00d41c454f7c1e194e0438629be9e3"
        "2e810f78912d1a9debebdf230e9393"
        "7b859b30af98e204f3cc4d894bfea2"
        "d32303a14f193ecc46d796f45e4f42"
        "fd970cd4353348b4d92bd7f5195a34"
        "c685185588d68ce5bd5b80b742d564"
        "40c26e41368fc9c9414d1978b54415"
        "29e70f4b041fc8fb953761c7cad40b"
        "a505d09f0f90d3b1070da3552c8674"
        "b41683e87629e29a3661689e0d97a2"
        "9fe6c6651eb15acbba535353f4b17f"
        "fd4e16b5e3888b050fad71e83162b3"
        "8b61b467244addbeb698062ff08ca1"
        "5e958dedfa09f02eb27583a2bbb2ce"
        "ef16a4e5f5d6d4053ae35729a9df3b"
        "5e9c64f816bf14da1bbe68a1f7efdf"
        "db3d97dac0a0639ef9337630a73543"
        "2223")
G = 0x2
PRIVATE_KEY = ("5b7818ca07690b0d90dc08b4c16154"
                "91e81778f0b6c06ce057d7c5aa0a47"
                "91f0f40e56aa1cb2a3a39829470ba4"
                "14044483b7ea83f82adb09fc40ad03"
                "d8e4769f95b25dcc5a21975d87aaaf"
                "148d03b500ac803ac226d527f319f9"
                "ed1a4bc5b5fb76ea4306ff2253cb42"
                "e9ee505726c2ae8a8990a29d5a2acd"
                "9fd98a6c909569012c67cdc2d521e1"
                "c3e8b0ff204dc080299c12830d00f9"
                "ad9c102f99cafdcdb488585c53327e"
                "29841a147f89f8b56943b90c22e9ad"
                "06f91f30202e9bc2834c4ab652a57d"
                "bea8d68adb28b05925e2d8d19373fc"
                "c23aca53a17cd1f5a4c116696294a1"
                "607dc1c128fd6a06f4378744f821ea"
                "ff5b169d85e9212eb20db43d303743"
                "4b")

PUBLIC_KEY = ("7a63a5c04d993573ed1b2e90e4c5a1"
        "1af95fadce1f0b6b713a843bd81b83"
        "1fe846a9a3870460830b7560debaa9"
        "84dbfca544f71ac38066abc9a0d43b"
        "561d692147b193178e88fef45b0521"
        "ab1441fba3aa7cbce9a64c9e07bd25"
        "e3738c0f551cc64e71be1b8fa2b2c5"
        "ec7a1fe9c80c3baa7fa86d091a3c0b"
        "71127287880f3f28aa55a6282bdf07"
        "8adc5e41a45081577d6558d53d6709"
        "ab26a9ddbeebef8748ab11ab1a95a4"
        "9158f4150477504a39de26e34cd88a"
        "35be1bceb7b04d0e1944295e24f0ed"
        "e3d0e9ab8f44ff9ec2a90e8d7b1efa"
        "39751429f8d665d03b23f0ec13a393"
        "54c31253481cf43daad1db8e449c95"
        "207fb9c345d129892a25ee6d7dac2c"
        "cc")