"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f!c+s-6t&^wa#-48ayx#yfd8g2aq2u4+3w=%3n6wfv#0+%f9q5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# P = (
#     "00b7b8209c149ac28024c4350dbb9c"
#     "9c86c4620ed696b79a20598deb3446"
#     "5ed151d706614e033c1eaca3333486"
#     "88ded0aa06ee0583792762985c9767"
#     "a13588e6db9a5bd7918112ffcf8853"
#     "b66c7379cbede03730591618c71a4d"
#     "2b1a133d77481350b07f141f1f110e"
#     "e96e04c9ccdb7245a55f99a28583e7"
#     "1f014ac0f89b94de1afb922a3aab9b"
#     "824a8d0f8a6b156c3de190d57d3149"
#     "807a7dd43ce920d4be635b0cad4794"
#     "70c30f061b1314346aa2caa3ece039"
#     "c53c4b56003c1d5ad9d877e19a21b5"
#     "173860d0ea692efe6fca511b9d5ebf"
#     "2d99306fe5560df48dc5cd68fbf204"
#     "217886550a53fb5ba6efa0fceb2209"
#     "dc36793aeb1c74f1ededb54712483b"
#     "1113")

# G = 0x2
# PRIVATE_KEY = (
#     "51609968bcc1103aa9e2ea6bde6442"
#     "943ab40c25bce0ef582b1bb9292b18"
#     "3fe99e2b6b45242ef3c04170b331c8"
#     "2646c8714ee98c8bf733e0ba99ffe5"
#     "93711e7704973bdaa039ec70756d38"
#     "b2bf645491717f27e5464aa6edcdb7"
#     "9eaaafe2f1e43292820c0da2afb39e"
#     "f10b3f9e81a64139d4dcc28abe8ed5"
#     "008f0a71b217841bf769d35e48c3c5"
#     "8d29268f9091d72933db2c2867f295"
#     "e7c7560e0aed4ebd1c0b97e5dff002"
#     "99a8c3b603453324d8ec147c10548f"
#     "6a3611e46472ee29f662d48fcfb2e2"
#     "28e485f095a7eb6606d1a1e1d90a69"
#     "049d509828ff35727d47460d05511d"
#     "e3624e4f3fb8c4655d78577bcf0de5"
#     "d553c3827e59e3ac7a1d6797e1a30f"
#     "a5")

# PUBLIC_KEY = (
#         "11a58660f9bb8b8b0ef44ee419f5e3"
#         "9a23c1b883c4449ae26dad2b8ae3ec"
#         "548e8378c2dea107990f00ef679fe5"
#         "603b26e8d30bc037ead013acd83801"
#         "4016cfa6739c350f080dd1da37cbee"
#         "c61508d6e9ba4a9eb16e9bbacf929f"
#         "d8f5b3317ce17444270b7d12340ab9"
#         "c3ce7a95624ab88b746a5b34f7ffb8"
#         "ca5b504ddf324070b5549a770666e9"
#         "4d617214d9ef2ee832937ae81ca389"
#         "b59c0a393da494fb6cd9dbc8e77f87"
#         "3b67523e35cf90345318458bfd09c7"
#         "faf6495c9a095716bf10e386cd64f2"
#         "bc9d5a18124e1c8021f2178480f941"
#         "50bf0572c5e472661aac23cc484e49"
#         "854aaa519b02b76de127dd1ad7f218"
#         "33728972e37a7dc3cd2acb1a9db596"
#         "17")

P = (
    "00b0bd0679a743d362eeaa68d6dacf"
    "065657d26d170208139c3f486dd11e"
    "facf0219c21c80cc55ed11b9e5874a"
    "c95d46de13e4f2b9f69d033fb2edce"
    "10e6d4209c0c11f6f4ed0de7e8a2d4"
    "0e66eeafe7743b5507bd2e1571f744"
    "cda42cb7647dd1d90bb0c92c3b9665"
    "16b968439eb4659944477daa2ce8c6"
    "479544f9a5fce7e4628126b41b99ee"
    "e93f92928d267fa541924f7278ce95"
    "709387915a7b2a64317e1bd61b36dd"
    "556cd3c2fbc5f2f61455b58abfd1c9"
    "3587e18124c0b63779a296b96757b5"
    "43530a6aba0c9b67b461ee834a3974"
    "dd7d52c1f3f0b0d9bf81e26a6f615d"
    "51c51308adfcbb310bfe26faa2254e"
    "4f61b7e41a88b99b5efe913624fe3f"
    "a16b"
)
PUBLIC_KEY = 65537
PRIVATE_KEY = (
    "57fcd3236f7d59d8afff10909e8060"
    "a44db689eee16909f248a31360ffee"
    "576eb14a2d0c862de5076527fb11e5"
    "6bd5a32bfe5844f29cba8854d90534"
    "eee5fe92118444112d8f35bc608bf7"
    "db90caec0cb6991f70346822c3ba72"
    "3260bcb07fdf20122ce20a6e63f251"
    "bcde4683d5459b671dbc572362838c"
    "11a9342c49db5c9c44eaae053dbae6"
    "6a9e743e73f40bfbd2a1bcd0829c86"
    "2c6ef63a7dbba46545a903a97b2f37"
    "b229d4fec8cd1d57adfac2e576af8e"
    "0ee23a1047854c11cc677bf788d532"
    "e91b9d2dde48308d80e26e0c7c745c"
    "a27080bb2b7151e060240b4847cb92"
    "75add5fae455a97ee18b6c4e608b5c"
    "533a3c6b7fecd336d04ea0b3f8de3f"
    "19"
)